FROM continuumio/miniconda3
MAINTAINER Andrea Giachetti <giachetti@cerm.unifi.it>
LABEL description="Container image to run AmberTools v20 using Conda"

RUN conda install -c conda-forge ambertools=20
